{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "959487b5_6b828c88",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 3650664
      },
      "writtenOn": "2024-10-23T16:23:37Z",
      "side": 1,
      "message": "Fixed the typo in the commit message",
      "revId": "2b7ae95a4e78c7efd03038d89605fcdeb30f7d7a",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "ee5bc39a_b7fad781",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1183889
      },
      "writtenOn": "2024-10-28T08:35:52Z",
      "side": 1,
      "message": "unfortunately, there are a lot of failing tests that require fixing",
      "revId": "2b7ae95a4e78c7efd03038d89605fcdeb30f7d7a",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "0e604639_646a4eb1",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 3650664
      },
      "writtenOn": "2024-10-28T08:43:10Z",
      "side": 1,
      "message": "I fail to see how they are related to the change",
      "parentUuid": "ee5bc39a_b7fad781",
      "revId": "2b7ae95a4e78c7efd03038d89605fcdeb30f7d7a",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "832167c5_7ffd7d34",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1183889
      },
      "writtenOn": "2024-10-28T08:51:45Z",
      "side": 1,
      "message": "I guess the expected tests\u0027 outputs require updating. For example, test`//message/fail/iterator-non-callable-2//instruction_scheduling` expects the old `at Function.from (\u003canonymous\u003e)` stack trace item while after your change it looks like `at Uint8Array.from (\u003canonymous\u003e)`.",
      "parentUuid": "0e604639_646a4eb1",
      "revId": "2b7ae95a4e78c7efd03038d89605fcdeb30f7d7a",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "95968efc_e7189d13",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1183889
      },
      "writtenOn": "2024-10-28T08:54:28Z",
      "side": 1,
      "message": "See the expected output template in `test/message/fail/iterator-non-callable-2.out`.\nTry to run the test suite locally: `tools/dev/gm.py x64.optdebug.check`.",
      "parentUuid": "832167c5_7ffd7d34",
      "revId": "2b7ae95a4e78c7efd03038d89605fcdeb30f7d7a",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "17112500_fb30e36e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 3650664
      },
      "writtenOn": "2024-10-28T08:57:08Z",
      "side": 1,
      "message": "Ah, I see. Thanks for the pointer. I\u0027ll see if I can reproduce them and update the expected output. But it\u0027ll take me a few days to find free time for it.",
      "parentUuid": "95968efc_e7189d13",
      "revId": "2b7ae95a4e78c7efd03038d89605fcdeb30f7d7a",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}