{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "6157017b_95431f52",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1132654
      },
      "writtenOn": "2021-04-09T15:47:24Z",
      "side": 1,
      "message": "Seems like we have to deal with https://crbug.com/1197508 as well",
      "revId": "a9755d4c2479dde742ade9737347a60aeba283b3",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}