{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "461909d1_07730e14",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1115956
      },
      "writtenOn": "2023-03-01T09:34:35Z",
      "side": 1,
      "message": "We could merge this bug into 13470. It\u0027s the same problem.",
      "revId": "d61e7d3e06ccf52a1ee8fa51a452d5dbba101082",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}