{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "10e4c0dd_8a6b20d6",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1283477
      },
      "writtenOn": "2021-10-28T14:03:51Z",
      "side": 1,
      "message": "Hi Tobias, PTAL at this fix + test for the case where we don\u0027t request fallback. The functions converting the arguments might still follow the error case, so we need to generate both in this case, too.",
      "revId": "d83d85717a3e1065180a0d58592024f688f20825",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}